[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --access-log"

[[services]]
name = "web"
http = true

[[services.ports]]
port = 8000
protocol = "http"
